#!/usr/bin/env node

import {
  access,
  cp,
  mkdir,
  readFile,
  rename,
  writeFile
} from 'node:fs/promises';
import { constants as fsConstants } from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const THIS_DIR = path.dirname(fileURLToPath(import.meta.url));
const DEFAULT_SOURCE = path.resolve(THIS_DIR, '..');
const EXCLUDED_PATHS = new Set([
  '.git',
  'node_modules',
  'coverage',
  '.next',
  'dist',
  'tmp',
  '.DS_Store'
]);

function parseArgs(argv) {
  const options = {
    source: DEFAULT_SOURCE,
    target: path.resolve(process.cwd(), 'opencode-cli-v2-extracted'),
    packageName: undefined,
    dryRun: false,
    force: false,
    json: false
  };

  for (let index = 0; index < argv.length; index += 1) {
    const token = argv[index];

    if (token === '--source') {
      options.source = argv[++index] ?? options.source;
      continue;
    }

    if (token.startsWith('--source=')) {
      options.source = token.slice('--source='.length);
      continue;
    }

    if (token === '--target') {
      options.target = argv[++index] ?? options.target;
      continue;
    }

    if (token.startsWith('--target=')) {
      options.target = token.slice('--target='.length);
      continue;
    }

    if (token === '--name') {
      options.packageName = argv[++index] ?? options.packageName;
      continue;
    }

    if (token.startsWith('--name=')) {
      options.packageName = token.slice('--name='.length);
      continue;
    }

    if (token === '--dry-run') {
      options.dryRun = true;
      continue;
    }

    if (token === '--force') {
      options.force = true;
      continue;
    }

    if (token === '--json') {
      options.json = true;
      continue;
    }
  }

  return options;
}

async function exists(filePath) {
  try {
    await access(filePath, fsConstants.F_OK);
    return true;
  } catch {
    return false;
  }
}

function normalizePackageName(targetPath, explicitName) {
  if (explicitName && explicitName.trim().length > 0) {
    return explicitName.trim();
  }

  return path
    .basename(targetPath)
    .toLowerCase()
    .replace(/[^a-z0-9._-]/g, '-')
    .replace(/--+/g, '-');
}

function shouldCopyPath(sourceRoot, sourcePath) {
  const relative = path.relative(sourceRoot, sourcePath);
  if (!relative || relative === '.') {
    return true;
  }

  const firstSegment = relative.split(path.sep)[0];
  return !EXCLUDED_PATHS.has(firstSegment);
}

function toErrorMessage(error) {
  if (error instanceof Error) {
    return error.message;
  }

  return String(error);
}

function buildReadme(packageName) {
  return `# ${packageName}

Standalone extraction of the OpenCode CLI v2 workspace.

## Quick start

\`\`\`bash
bun install
bun test
\`\`\`

## Migration utilities

- \`bun scripts/migrate-to-v2.mjs --source <legacy-root> --target <target-root>\`
- \`bun scripts/verify-adapter.mjs\`
- \`bun scripts/extract-repo.mjs --target ../${packageName}\`

## Layout

\`\`\`text
.
├── src/
├── tests/
├── scripts/
├── docs/
└── .github/workflows/
\`\`\`

Generated by \`scripts/extract-repo.mjs\`.
`;
}

async function updatePackageJson(sourceRoot, targetRoot, packageName, dryRun) {
  const packagePath = path.resolve(targetRoot, 'package.json');
  const sourcePackagePath = path.resolve(sourceRoot, 'package.json');
  const packageReadPath = dryRun ? sourcePackagePath : packagePath;
  const raw = await readFile(packageReadPath, 'utf8');
  const parsed = JSON.parse(raw);

  parsed.name = packageName;
  parsed.private = false;
  parsed.description = 'Standalone OpenCode CLI v2 repository';
  parsed.scripts = {
    ...(parsed.scripts ?? {}),
    'migrate:to-v2': 'bun scripts/migrate-to-v2.mjs',
    'verify:adapters': 'bun scripts/verify-adapter.mjs',
    'extract:repo': 'bun scripts/extract-repo.mjs'
  };

  if (!dryRun) {
    await writeFile(packagePath, `${JSON.stringify(parsed, null, 2)}\n`, 'utf8');
  }

  return packagePath;
}

async function ensureRepoStructure(targetRoot, dryRun) {
  const requiredDirs = [
    'src',
    'tests',
    'scripts',
    'docs',
    '.github/workflows',
    '.opencode/data'
  ];

  const created = [];
  for (const dir of requiredDirs) {
    const absolute = path.resolve(targetRoot, dir);
    created.push(absolute);
    if (!dryRun) {
      await mkdir(absolute, { recursive: true });
    }
  }

  return created;
}

async function ensureGitignore(targetRoot, dryRun) {
  const filePath = path.resolve(targetRoot, '.gitignore');
  const baseline = ['node_modules/', 'coverage/', '.DS_Store', '.env', '.env.*'];
  const existing = (await exists(filePath)) ? await readFile(filePath, 'utf8') : '';

  const merged = [...new Set(existing.split(/\r?\n/g).concat(baseline).map((line) => line.trim()).filter(Boolean))];
  if (!dryRun) {
    await writeFile(filePath, `${merged.join('\n')}\n`, 'utf8');
  }

  return filePath;
}

async function writeReadme(targetRoot, packageName, dryRun) {
  const readmePath = path.resolve(targetRoot, 'README.md');
  const backupPath = path.resolve(targetRoot, 'README.legacy.md');

  if (!dryRun && (await exists(readmePath)) && !(await exists(backupPath))) {
    await rename(readmePath, backupPath);
  }

  if (!dryRun) {
    await writeFile(readmePath, buildReadme(packageName), 'utf8');
  }

  return {
    readmePath,
    backupPath: (await exists(backupPath)) ? backupPath : undefined
  };
}

function printHuman(summary) {
  console.log('OpenCode CLI v2 extraction report');
  console.log('==============================');
  console.log(`source: ${summary.source}`);
  console.log(`target: ${summary.target}`);
  console.log(`package: ${summary.packageName}`);
  console.log(`dryRun: ${summary.dryRun}`);
  console.log('');

  console.log(`copied: ${summary.copied}`);
  console.log(`package_json: ${summary.packagePath}`);
  console.log(`gitignore: ${summary.gitignorePath}`);
  console.log(`readme: ${summary.readme.readmePath}`);
  if (summary.readme.backupPath) {
    console.log(`readme_backup: ${summary.readme.backupPath}`);
  }

  console.log('');
  console.log('ensured_dirs:');
  for (const dir of summary.createdDirs) {
    console.log(`  - ${dir}`);
  }

  if (summary.issues.warnings.length > 0) {
    console.log('');
    console.log('warnings:');
    for (const warning of summary.issues.warnings) {
      console.log(`  - ${warning}`);
    }
  }

  if (summary.issues.errors.length > 0) {
    console.log('');
    console.log('errors:');
    for (const error of summary.issues.errors) {
      console.log(`  - ${error}`);
    }
  }
}

async function main() {
  const options = parseArgs(process.argv.slice(2));
  const sourceRoot = path.resolve(options.source);
  const targetRoot = path.resolve(options.target);
  const packageName = normalizePackageName(targetRoot, options.packageName);

  const issues = {
    warnings: [],
    errors: []
  };

  if (!(await exists(sourceRoot))) {
    issues.errors.push(`Source workspace does not exist: ${sourceRoot}`);
  }

  const targetExists = await exists(targetRoot);
  if (targetExists && !options.force) {
    issues.errors.push(`Target already exists (use --force): ${targetRoot}`);
  }

  if (targetRoot.startsWith(sourceRoot + path.sep)) {
    issues.errors.push('Target cannot be nested inside source workspace');
  }

  if (issues.errors.length > 0) {
    const failed = {
      source: sourceRoot,
      target: targetRoot,
      packageName,
      dryRun: options.dryRun,
      copied: false,
      packagePath: path.resolve(targetRoot, 'package.json'),
      gitignorePath: path.resolve(targetRoot, '.gitignore'),
      readme: {
        readmePath: path.resolve(targetRoot, 'README.md')
      },
      createdDirs: [],
      issues
    };

    if (options.json) {
      console.log(JSON.stringify(failed, null, 2));
    } else {
      printHuman(failed);
    }

    process.exit(1);
  }

  if (!options.dryRun) {
    await mkdir(targetRoot, { recursive: true });
    await cp(sourceRoot, targetRoot, {
      recursive: true,
      force: true,
      preserveTimestamps: true,
      filter: (sourcePath) => shouldCopyPath(sourceRoot, sourcePath)
    });
  }

  const packagePath = await updatePackageJson(sourceRoot, targetRoot, packageName, options.dryRun);
  const createdDirs = await ensureRepoStructure(targetRoot, options.dryRun);
  const gitignorePath = await ensureGitignore(targetRoot, options.dryRun);
  const readme = await writeReadme(targetRoot, packageName, options.dryRun);

  const summary = {
    source: sourceRoot,
    target: targetRoot,
    packageName,
    dryRun: options.dryRun,
    copied: true,
    packagePath,
    gitignorePath,
    readme,
    createdDirs,
    issues
  };

  if (options.json) {
    console.log(JSON.stringify(summary, null, 2));
  } else {
    printHuman(summary);
  }

  process.exit(issues.errors.length > 0 ? 1 : 0);
}

await main();
