#!/bin/bash

# MCP Server Reference for OpenCode
# NOTE: canonical source-of-truth is opencode-config/opencode.json

echo "=========================================="
echo " OpenCode MCP Server Reference"
echo "=========================================="
echo ""
echo "Canonical config: opencode-config/opencode.json"
echo "Runtime merged config: ~/.config/opencode/opencode.json"
echo ""
echo "Current canonical MCP surface:"
echo ""
echo "  - supermemory (remote)"
echo "      URL: https://mcp.supermemory.ai/mcp"
echo "      Requires: SUPERMEMORY_API_KEY"
echo "  - context7 (remote)"
echo "      URL: https://mcp.context7.com/mcp"
echo "      Requires: none"
echo "  - playwright (local)"
echo "      Command: bunx @playwright/mcp@0.0.64"
echo "  - sequentialthinking (local)"
echo "      Command: bunx -y @modelcontextprotocol/server-sequential-thinking"
echo "  - websearch (local)"
echo "      Command: bunx -y @ignidor/web-search-mcp"
echo "  - grep (local)"
echo "      Command: uvx grep-mcp"
echo "  - distill (local)"
echo "      Command: bun scripts/run-distill-mcp.mjs serve --lazy"
echo "  - opencode-dashboard-launcher (local, disabled by default)"
echo "      Command: bun packages/opencode-dashboard-launcher/src/index.js"
echo "  - opencode-memory-graph (local)"
echo "      Command: bun packages/opencode-memory-graph/src/mcp-server.mjs"
echo "  - opencode-context-governor (local)"
echo "      Command: bun packages/opencode-context-governor/src/mcp-server.mjs"
echo "  - opencode-runbooks (local)"
echo "      Command: bun packages/opencode-runbooks/src/mcp-server.mjs"
echo ""
echo "=========================================="
echo " Prerequisites Check"
echo "=========================================="
echo ""

command -v bun >/dev/null 2>&1 && echo "  [OK] Bun $(bun --version)" || echo "  [MISSING] Bun — install from https://bun.sh"
command -v bunx >/dev/null 2>&1 && echo "  [OK] bunx available" || echo "  [MISSING] bunx — included with Bun"
command -v node >/dev/null 2>&1 && echo "  [OK] Node.js $(node --version)" || echo "  [MISSING] Node.js — required by setup and compatibility scripts"
command -v uvx >/dev/null 2>&1 && echo "  [OK] uvx available" || echo "  [MISSING] uvx — run: pip install --user uv"
[ -n "$SUPERMEMORY_API_KEY" ] && echo "  [OK] SUPERMEMORY_API_KEY set" || echo "  [WARN] SUPERMEMORY_API_KEY missing (supermemory MCP will fail)"
echo ""
