#!/usr/bin/env node

import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';
import { resolveRoot } from './resolve-root.mjs';
import { synthesize } from './synthesize-meta-kb.mjs';

const ROOT = resolveRoot();
const POLICY_PATH = path.join(ROOT, 'opencode-config', 'learning-update-policy.json');
const UPDATES_DIR = path.join(ROOT, 'opencode-config', 'learning-updates');
const HASHES_PATH = path.join(ROOT, 'opencode-config', '.governance-hashes.json');
const HASH_ALGORITHM = 'SHA-256';
const HASH_HEX_LENGTH = 64;
const CONFIG_EXTENSIONS = new Set(['.json', '.yaml', '.yml']);

function parseArgs(argv) {
  const args = { staged: false, base: null, verifyHashes: false, generateHashes: false };
  for (let i = 2; i < argv.length; i += 1) {
    const token = argv[i];
    if (token === '--staged') {
      args.staged = true;
    } else if (token === '--base') {
      args.base = argv[i + 1] ?? null;
      i += 1;
    } else if (token === '--verify-hashes') {
      args.verifyHashes = true;
    } else if (token === '--generate-hashes') {
      args.generateHashes = true;
    }
  }
  return args;
}

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, 'utf8'));
}

function normalizePath(input) {
  return input.replace(/\\/g, '/').replace(/^\.\//, '');
}

function getChangedFiles({ staged, base }) {
  if (!staged && base == null) {
    const trackedOut = execSync('git diff --name-only', { cwd: ROOT, encoding: 'utf8' }).trim();
    const untrackedOut = execSync('git ls-files --others --exclude-standard', {
      cwd: ROOT,
      encoding: 'utf8'
    }).trim();
    const combined = [trackedOut, untrackedOut].filter(Boolean).join('\n');
    if (!combined) {
      return [];
    }
    return combined.split('\n').map((line) => line.trim()).filter(Boolean);
  }

  // Sanitize base parameter to prevent command injection
  const sanitizedBase = base?.replace(/[^a-zA-Z0-9/_.\-]/g, '');
  if (base && base !== sanitizedBase) {
    console.error('[learning-gate] WARNING: base parameter contained invalid characters, sanitized');
  }
  const safeBase = sanitizedBase || 'HEAD';

  const cmd = staged
    ? 'git diff --cached --name-only'
    : `git diff --name-only ${safeBase}...HEAD`;

  const output = execSync(cmd, { cwd: ROOT, encoding: 'utf8' }).trim();
  if (!output) {
    return [];
  }
  return output.split('\n').map((line) => line.trim()).filter(Boolean);
}

function getTrackedFiles() {
  const output = execSync('git ls-files', { cwd: ROOT, encoding: 'utf8' }).trim();
  if (!output) {
    return [];
  }
  return output.split('\n').map((line) => line.trim()).filter(Boolean);
}

function matchPath(file, patterns) {
  const normalizedFile = normalizePath(file);
  return patterns.some((prefix) => normalizedFile.startsWith(normalizePath(prefix)));
}

function isLearningUpdateFile(file) {
  const normalizedFile = normalizePath(file);
  return normalizedFile.startsWith('opencode-config/learning-updates/') && normalizedFile.endsWith('.json');
}

function isMetaKBAutoGenerated(learningUpdateFiles) {
  for (const relFile of learningUpdateFiles) {
    try {
      const absPath = path.join(ROOT, relFile);
      if (!fs.existsSync(absPath)) continue;
      const payload = readJson(absPath);
      if (payload.source === 'meta-kb-auto') return true;
    } catch { /* skip unreadable files */ }
  }
  return false;
}

function triggerMetaKBSynthesis(learningUpdateFiles) {
  if (isMetaKBAutoGenerated(learningUpdateFiles)) {
    console.log('learning-gate: skipping meta-KB synthesis (auto-generated commit)');
    return;
  }

  const synthScript = path.join(ROOT, 'scripts', 'synthesize-meta-kb.mjs');
  if (!fs.existsSync(synthScript)) {
    console.log('learning-gate: meta-KB synthesis script not found, skipping');
    return;
  }

  try {
    execSync(`node "${synthScript}"`, { cwd: ROOT, encoding: 'utf8', stdio: 'pipe', timeout: 30_000 });
    console.log('learning-gate: meta-KB index refreshed');
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.warn(`learning-gate: WARNING meta-KB synthesis failed (non-blocking): ${msg}`);
  }
}

function isGovernedConfigFile(file, policy) {
  const normalizedFile = normalizePath(file);

  if (!matchPath(normalizedFile, policy.governed_paths)) {
    return false;
  }

  if (normalizedFile === 'opencode-config/.governance-hashes.json') {
    return false;
  }

  if (normalizedFile.startsWith('opencode-config/learning-updates/')) {
    return false;
  }

  if (normalizedFile === 'package.json') {
    return true;
  }

  if (!normalizedFile.startsWith('opencode-config/')) {
    return false;
  }

  return CONFIG_EXTENSIONS.has(path.extname(normalizedFile));
}

async function hashFile(filePath) {
  const data = fs.readFileSync(filePath);
  const digest = await crypto.subtle.digest(HASH_ALGORITHM, data);
  return Array.from(new Uint8Array(digest), (byte) => byte.toString(16).padStart(2, '0')).join('');
}

function sortedObject(input) {
  const entries = Object.entries(input).sort(([a], [b]) => a.localeCompare(b));
  return Object.fromEntries(entries);
}

async function computeGovernanceHashes(policy) {
  const files = getTrackedFiles().filter((file) => isGovernedConfigFile(file, policy));
  files.sort((a, b) => a.localeCompare(b));

  const hashes = {};
  for (const relFile of files) {
    hashes[normalizePath(relFile)] = await hashFile(path.join(ROOT, relFile));
  }

  return {
    version: 1,
    algorithm: HASH_ALGORITHM,
    generated_at: new Date().toISOString(),
    files: sortedObject(hashes)
  };
}

function readKnownHashes() {
  if (!fs.existsSync(HASHES_PATH)) {
    return null;
  }
  return readJson(HASHES_PATH);
}

function writeKnownHashes(payload) {
  fs.writeFileSync(HASHES_PATH, `${JSON.stringify(payload, null, 2)}\n`);
}

function normalizeHashesPayload(payload) {
  const clone = JSON.parse(JSON.stringify(payload));
  delete clone.generated_at;
  return clone;
}

function prepareHashesOutput(nextHashes, existingHashes) {
  if (!existingHashes) {
    return { payload: nextHashes, changed: true };
  }

  const normalizedNext = normalizeHashesPayload(nextHashes);
  const normalizedExisting = normalizeHashesPayload(existingHashes);
  const changed = JSON.stringify(normalizedNext) !== JSON.stringify(normalizedExisting);

  if (!changed) {
    return {
      payload: {
        ...nextHashes,
        generated_at: existingHashes.generated_at || nextHashes.generated_at
      },
      changed: false
    };
  }

  return { payload: nextHashes, changed: true };
}

function isValidHash(value) {
  return typeof value === 'string' && /^[a-f0-9]+$/i.test(value) && value.length === HASH_HEX_LENGTH;
}

function compareHashes(knownHashes, currentHashes) {
  const knownEntries = knownHashes?.files && typeof knownHashes.files === 'object' ? knownHashes.files : {};
  const currentEntries = currentHashes.files;

  const missingFiles = [];
  const mismatchedFiles = [];
  const unmanagedFiles = [];

  for (const [file, expectedHash] of Object.entries(knownEntries)) {
    const actualHash = currentEntries[file];
    if (!actualHash) {
      missingFiles.push(file);
      continue;
    }
    if (!isValidHash(expectedHash) || expectedHash.toLowerCase() !== actualHash.toLowerCase()) {
      mismatchedFiles.push(file);
    }
  }

  for (const file of Object.keys(currentEntries)) {
    if (!(file in knownEntries)) {
      unmanagedFiles.push(file);
    }
  }

  return {
    missingFiles,
    mismatchedFiles,
    unmanagedFiles
  };
}

function formatHashDiff(diff) {
  const lines = [];
  if (diff.missingFiles.length > 0) {
    lines.push(`- missing files: ${diff.missingFiles.join(', ')}`);
  }
  if (diff.mismatchedFiles.length > 0) {
    lines.push(`- mismatched files: ${diff.mismatchedFiles.join(', ')}`);
  }
  if (diff.unmanagedFiles.length > 0) {
    lines.push(`- unmanaged files: ${diff.unmanagedFiles.join(', ')}`);
  }
  return lines.join('\n');
}

function hasHashDiff(diff) {
  return diff.missingFiles.length > 0 || diff.mismatchedFiles.length > 0 || diff.unmanagedFiles.length > 0;
}

function enforceGovernanceHashes(knownHashes, currentHashes, verifyHashes) {
  if (!knownHashes) {
    const message =
      'learning-gate: governance hash baseline missing at opencode-config/.governance-hashes.json. Run --generate-hashes after legitimate config updates.';
    if (verifyHashes) {
      throw new Error(message);
    }
    console.warn(`learning-gate: WARNING ${message}`);
    return;
  }

  const diff = compareHashes(knownHashes, currentHashes);
  if (!hasHashDiff(diff)) {
    return;
  }

  const details = formatHashDiff(diff);
  const message = [
    'learning-gate: governance hash mismatch detected.',
    details,
    '- this blocks runtime/manual config drift that bypasses git-diff-only governance checks.',
    "- run 'node scripts/learning-gate.mjs --generate-hashes' after approved config changes."
  ].join('\n');

  if (verifyHashes) {
    throw new Error(message);
  }

  console.warn(`learning-gate: WARNING\n${message}`);
}

function validateLearningUpdate(update, file, policy, governedChanges) {
  const requiredTop = policy.required_update_fields || [];
  for (const field of requiredTop) {
    if (!(field in update)) {
      throw new Error(`${file}: missing required field '${field}'`);
    }
  }

  if (!Array.isArray(update.affected_paths) || update.affected_paths.length === 0 || !update.affected_paths.every((p) => typeof p === 'string')) {
    throw new Error(`${file}: 'affected_paths' must be a non-empty array`);
  }

  const normalizedGoverned = governedChanges.map(normalizePath);
  const normalizedAffected = update.affected_paths.map(normalizePath);
  const affectedGovernedOverlap = normalizedAffected.some((affected) =>
    normalizedGoverned.some((changed) => changed === affected || changed.startsWith(affected) || affected.startsWith(changed))
  );
  if (!affectedGovernedOverlap) {
    throw new Error(`${file}: affected_paths must overlap at least one governed changed file`);
  }

  const requiredValidation = policy.required_validation_fields || [];
  for (const field of requiredValidation) {
    if (!(field in update.validation)) {
      throw new Error(`${file}: validation missing '${field}'`);
    }
  }

  const allowedStatus = new Set(policy.allowed_validation_status || ['pass', 'fail', 'not-run']);
  for (const field of requiredValidation) {
    const value = update.validation[field];
    if (!allowedStatus.has(value)) {
      throw new Error(`${file}: validation.${field} must be one of pass|fail|not-run`);
    }
  }

  const allowedRisk = new Set(policy.allowed_risk_levels || ['low', 'medium', 'high']);
  if (!allowedRisk.has(update.risk_level)) {
    throw new Error(`${file}: risk_level must be one of low|medium|high`);
  }

  const riskRequirements = policy.require_pass_for_risk || {};
  const mustPassFields = riskRequirements[update.risk_level] || [];
  for (const field of mustPassFields) {
    if (update.validation[field] !== 'pass') {
      throw new Error(`${file}: risk_level '${update.risk_level}' requires validation.${field} to be 'pass'`);
    }
  }
}



async function main() {
  const args = parseArgs(process.argv);
  const policy = readJson(POLICY_PATH);
  const knownHashes = readKnownHashes();

  const currentHashes = await computeGovernanceHashes(policy);

  if (args.generateHashes) {
    const prepared = prepareHashesOutput(currentHashes, knownHashes);
    writeKnownHashes(prepared.payload);
    console.log(`learning-gate: generated governance hashes at ${normalizePath(path.relative(ROOT, HASHES_PATH))}`);
    console.log(`- governed config files: ${Object.keys(currentHashes.files).length}`);
    return;
  }

  // Hash checks run on every invocation so runtime/manual edits cannot evade governance by avoiding git-diff contexts.
  enforceGovernanceHashes(knownHashes, currentHashes, args.verifyHashes);

  const changedFiles = getChangedFiles(args);

  if (changedFiles.length === 0) {
    console.log('learning-gate: no changed files, skipping');
    return;
  }

  const governedChanges = changedFiles.filter((file) => matchPath(file, policy.governed_paths));
  if (governedChanges.length === 0) {
    console.log('learning-gate: no governed changes detected');
    return;
  }

  const learningUpdateFiles = changedFiles.filter(isLearningUpdateFile);
  if (learningUpdateFiles.length === 0) {
    throw new Error(
      'learning-gate: governed files changed but no learning update record added under opencode-config/learning-updates/'
    );
  }

  if (!fs.existsSync(UPDATES_DIR)) {
    throw new Error('learning-gate: learning-updates directory is missing');
  }

  for (const relFile of learningUpdateFiles) {
    const absPath = path.join(ROOT, relFile);
    if (!fs.existsSync(absPath)) {
      throw new Error(`learning-gate: update file not found: ${relFile}`);
    }
    const payload = readJson(absPath);
    validateLearningUpdate(payload, relFile, policy, governedChanges);
  }

  console.log('learning-gate: PASS');
  console.log(`- governed changes: ${governedChanges.length}`);
  console.log(`- learning updates: ${learningUpdateFiles.length}`);

  // Post-validation: refresh meta-KB index so downstream consumers stay current
  triggerMetaKBSynthesis(learningUpdateFiles);

  const refreshedHashes = await computeGovernanceHashes(policy);
  const preparedHashes = prepareHashesOutput(refreshedHashes, knownHashes);
  if (preparedHashes.changed) {
    writeKnownHashes(preparedHashes.payload);
    console.log('learning-gate: governance hashes refreshed');
  }
}

// `import.meta.main` is Bun-specific; fall back to argv[1] check for Node.js compatibility
import { fileURLToPath } from 'node:url';
const _isEntryPoint = (typeof import.meta.main === 'boolean')
  ? import.meta.main
  : process.argv[1] === fileURLToPath(import.meta.url);

if (_isEntryPoint) {
  try {
    await main();
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    console.error(message);
    process.exit(1);
  }
}

export { normalizeHashesPayload, prepareHashesOutput, main };
